### ISSUE TITLE
"Create project" button not calling the modal when clicked

### ISSUE THREAD

**Issue by silicon755** [lcharette/UF_FormGeneratorExample#3]
Trying out [UF_FormGeneratorExample](https://github.com/lcharette/UF_FormGeneratorExample) just to get a hang of it but I'm running into issues. I can't get the modal with fields to create a new project working. I have attached a screenshot with console errors. Kindly advice.
![Screenshot from 2019-11-27 17-51-37](https://user-images.githubusercontent.com/22223504/69735562-f047b880-1141-11ea-8602-607c239b822e.png)

**Comment by lcharette** [comment]
I couldn't replicate, but you can give this package new 3.0.0 version a try. Old version used an old version of FormGenerator.

See updated instructions here : https://github.com/lcharette/UF_FormGeneratorExample#installation


I'll reopen if you still have the issue.

**Comment by silicon755** [comment]
The problem is still persistent and now the sidebar menu of UserFrosting has disappeared as you can see from the attached screenshot.
![Screenshot from 2019-11-28 09-14-19](https://user-images.githubusercontent.com/22223504/69781698-f11f2f80-11bf-11ea-966c-0ef16faa4c4c.png)

**Comment by lcharette** [comment]
Menu is missing because you're not logged in.

Did you run bake command ?

**Comment by silicon755** [comment]
> Menu is missing because you're not logged in.
> 
> Did you run bake command ?

I did ran bake command with no luck

**Comment by silicon755** [comment]
I get a 404 status code upon clicking the "Create project" button as shown in the screenshot below. When I navigate to `http://http://localhost/formgenerator/new ` I get the unstyled form, screenshot attached too. Kindly let me know what I could be missing to have the form modal triggered.

![Screenshot from 2019-11-30 16-55-13](https://user-images.githubusercontent.com/22223504/69901463-f7193a00-1392-11ea-9769-7241856d3330.png)
![Firefox_Screenshot_2019-11-30T03-57-23 126Z](https://user-images.githubusercontent.com/22223504/69897205-46427900-1359-11ea-9efa-218db5710c31.png)

**Comment by lcharette** [comment]
Can you check out the "Network" tab of the inspector, it should show the request details. 

The unstyled page is normal.

I can't replicate your issue. I suggest you try a fresh install ?

**Comment by silicon755** [comment]
Just tried with fresh install but still experiencing the same problem. The "Network" tab screenshot is attached.
![Screenshot from 2019-12-02 08-52-03](https://user-images.githubusercontent.com/22223504/69934172-399d5c80-14e2-11ea-8008-88a6f4ac95dc.png)

**Comment by lcharette** [comment]
Can you run those two command and post the result? 

```
php bakery debug 
``` 

```
php bakery route:list
```

**Comment by silicon755** [comment]
`root@webmaster:/var/www/html/playground# php bakery debug

UserFrosting
============

UserFrosing version : 4.3.0
OS Name : Linux
Project Root : /var/www/html/playground
Environment mode : development
PHP Version : 7.3.12-1
Node Version : v12.3.1
NPM Version : 6.9.0

Loaded Sprinkles
================

 ---------------------- -------------------------------------------- ------------------------------------------------------------- 
  Sprinkle               Calculated Namespace                         Calculated Path                                              
 ---------------------- -------------------------------------------- ------------------------------------------------------------- 
  core                   UserFrosting\Sprinkle\Core                   /var/www/html/playground/app/sprinkles/core                  
  account                UserFrosting\Sprinkle\Account                /var/www/html/playground/app/sprinkles/account               
  admin                  UserFrosting\Sprinkle\Admin                  /var/www/html/playground/app/sprinkles/admin                 
  FormGenerator          UserFrosting\Sprinkle\FormGenerator          /var/www/html/playground/app/sprinkles/FormGenerator         
  FormGeneratorExample   UserFrosting\Sprinkle\FormGeneratorExample   /var/www/html/playground/app/sprinkles/FormGeneratorExample  
 ---------------------- -------------------------------------------- ------------------------------------------------------------- 


Database config
===============

DRIVER : mysql
HOST : localhost
PORT : 3306
DATABASE : playground
USERNAME : root
PASSWORD : *********

Testing database connection...
==============================

Database connection successful

                                                                                                    
 [OK] Ready to bake !                                                                               
                                                                                                    

`

**Comment by silicon755** [comment]
`root@webmaster:/var/www/html/playground# php bakery route:list

Registered Routes
=================

 -------- ----------------------------------------- ----------------- ------------------------------------------------------------------------------------------------- 
  Method   URI                                       Name              Action                                                                                           
 -------- ----------------------------------------- ----------------- ------------------------------------------------------------------------------------------------- 
  GET      /                                         index             UserFrosting\Sprinkle\Core\Controller\CoreController:pageIndex                                   
  GET      /about                                                      UserFrosting\Sprinkle\Core\Controller\CoreController:pageAbout                                   
  GET      /account/captcha                                            UserFrosting\Sprinkle\Account\Controller\AccountController:imageCaptcha                          
  GET      /account/check-username                                     UserFrosting\Sprinkle\Account\Controller\AccountController:checkUsername                         
  GET      /account/forgot-password                  forgot-password   UserFrosting\Sprinkle\Account\Controller\AccountController:pageForgotPassword                    
  POST     /account/forgot-password                                    UserFrosting\Sprinkle\Account\Controller\AccountController:forgotPassword                        
  POST     /account/login                                              UserFrosting\Sprinkle\Account\Controller\AccountController:login                                 
  GET      /account/logout                                             UserFrosting\Sprinkle\Account\Controller\AccountController:logout                                
  GET      /account/register                         register          UserFrosting\Sprinkle\Account\Controller\AccountController:pageRegister                          
  POST     /account/register                                           UserFrosting\Sprinkle\Account\Controller\AccountController:register                              
  GET      /account/resend-verification                                UserFrosting\Sprinkle\Account\Controller\AccountController:pageResendVerification                
  POST     /account/resend-verification                                UserFrosting\Sprinkle\Account\Controller\AccountController:resendVerification                    
  POST     /account/set-password                                       UserFrosting\Sprinkle\Account\Controller\AccountController:setPassword                           
  GET      /account/set-password/confirm                               UserFrosting\Sprinkle\Account\Controller\AccountController:pageResetPassword                     
  GET      /account/set-password/deny                                  UserFrosting\Sprinkle\Account\Controller\AccountController:denyResetPassword                     
  POST     /account/settings                         settings          UserFrosting\Sprinkle\Account\Controller\AccountController:settings                              
  GET      /account/settings                                           UserFrosting\Sprinkle\Account\Controller\AccountController:pageSettings                          
  POST     /account/settings/profile                                   UserFrosting\Sprinkle\Account\Controller\AccountController:profile                               
  GET      /account/sign-in                          login             UserFrosting\Sprinkle\Account\Controller\AccountController:pageSignIn                            
  GET      /account/suggest-username                                   UserFrosting\Sprinkle\Account\Controller\AccountController:suggestUsername                       
  GET      /account/verify                                             UserFrosting\Sprinkle\Account\Controller\AccountController:verify                                
  GET      /activities                               uri_activities    UserFrosting\Sprinkle\Admin\Controller\ActivityController:pageList                               
  GET      /alerts                                                     UserFrosting\Sprinkle\Core\Controller\CoreController:jsonAlerts                                  
  GET      /api/activities                                             UserFrosting\Sprinkle\Admin\Controller\ActivityController:getList                                
  POST     /api/dashboard/clear-cache                                  UserFrosting\Sprinkle\Admin\Controller\AdminController:clearCache                                
  GET      /api/groups                                                 UserFrosting\Sprinkle\Admin\Controller\GroupController:getList                                   
  POST     /api/groups                                                 UserFrosting\Sprinkle\Admin\Controller\GroupController:create                                    
  GET      /api/groups/g/{slug}                                        UserFrosting\Sprinkle\Admin\Controller\GroupController:getInfo                                   
  DELETE   /api/groups/g/{slug}                                        UserFrosting\Sprinkle\Admin\Controller\GroupController:delete                                    
  PUT      /api/groups/g/{slug}                                        UserFrosting\Sprinkle\Admin\Controller\GroupController:updateInfo                                
  GET      /api/groups/g/{slug}/users                                  UserFrosting\Sprinkle\Admin\Controller\GroupController:getUsers                                  
  GET      /api/permissions                                            UserFrosting\Sprinkle\Admin\Controller\PermissionController:getList                              
  GET      /api/permissions/p/{id}                                     UserFrosting\Sprinkle\Admin\Controller\PermissionController:getInfo                              
  GET      /api/permissions/p/{id}/users                               UserFrosting\Sprinkle\Admin\Controller\PermissionController:getUsers                             
  POST     /api/roles                                                  UserFrosting\Sprinkle\Admin\Controller\RoleController:create                                     
  GET      /api/roles                                                  UserFrosting\Sprinkle\Admin\Controller\RoleController:getList                                    
  DELETE   /api/roles/r/{slug}                                         UserFrosting\Sprinkle\Admin\Controller\RoleController:delete                                     
  PUT      /api/roles/r/{slug}                                         UserFrosting\Sprinkle\Admin\Controller\RoleController:updateInfo                                 
  GET      /api/roles/r/{slug}                                         UserFrosting\Sprinkle\Admin\Controller\RoleController:getInfo                                    
  GET      /api/roles/r/{slug}/permissions                             UserFrosting\Sprinkle\Admin\Controller\RoleController:getPermissions                             
  GET      /api/roles/r/{slug}/users                                   UserFrosting\Sprinkle\Admin\Controller\RoleController:getUsers                                   
  PUT      /api/roles/r/{slug}/{field}                                 UserFrosting\Sprinkle\Admin\Controller\RoleController:updateField                                
  POST     /api/users                                                  UserFrosting\Sprinkle\Admin\Controller\UserController:create                                     
  GET      /api/users                                                  UserFrosting\Sprinkle\Admin\Controller\UserController:getList                                    
  DELETE   /api/users/u/{user_name}                                    UserFrosting\Sprinkle\Admin\Controller\UserController:delete                                     
  GET      /api/users/u/{user_name}                                    UserFrosting\Sprinkle\Admin\Controller\UserController:getInfo                                    
  PUT      /api/users/u/{user_name}                                    UserFrosting\Sprinkle\Admin\Controller\UserController:updateInfo                                 
  GET      /api/users/u/{user_name}/activities                         UserFrosting\Sprinkle\Admin\Controller\UserController:getActivities                              
  POST     /api/users/u/{user_name}/password-reset                     UserFrosting\Sprinkle\Admin\Controller\UserController:createPasswordReset                        
  GET      /api/users/u/{user_name}/permissions                        UserFrosting\Sprinkle\Admin\Controller\UserController:getPermissions                             
  GET      /api/users/u/{user_name}/roles                              UserFrosting\Sprinkle\Admin\Controller\UserController:getRoles                                   
  PUT      /api/users/u/{user_name}/{field}                            UserFrosting\Sprinkle\Admin\Controller\UserController:updateField                                
  GET      /assets-raw/{url:.+}                                        UserFrosting\Sprinkle\Core\Controller\CoreController:getAsset                                    
  GET      /dashboard                                dashboard         UserFrosting\Sprinkle\Admin\Controller\AdminController:pageDashboard                             
  GET      /formgenerator                                              UserFrosting\Sprinkle\FormGeneratorExample\Controller\FormGeneratorExampleController:main        
  POST     /formgenerator                                              UserFrosting\Sprinkle\FormGeneratorExample\Controller\FormGeneratorExampleController:create      
  GET      /formgenerator/new                                          UserFrosting\Sprinkle\FormGeneratorExample\Controller\FormGeneratorExampleController:createForm  
  PUT      /formgenerator/{project_id:[0-9]+}                          UserFrosting\Sprinkle\FormGeneratorExample\Controller\FormGeneratorExampleController:update      
  DELETE   /formgenerator/{project_id:[0-9]+}                          UserFrosting\Sprinkle\FormGeneratorExample\Controller\FormGeneratorExampleController:delete      
  GET      /formgenerator/{project_id:[0-9]+}/edit                     UserFrosting\Sprinkle\FormGeneratorExample\Controller\FormGeneratorExampleController:editForm    
  GET      /forms/confirm                                              UserFrosting\Sprinkle\FormGenerator\Controller\FormGeneratorController:confirm                   
  GET      /groups                                   uri_groups        UserFrosting\Sprinkle\Admin\Controller\GroupController:pageList                                  
  GET      /groups/g/{slug}                                            UserFrosting\Sprinkle\Admin\Controller\GroupController:pageInfo                                  
  GET      /legal                                                      UserFrosting\Sprinkle\Core\Controller\CoreController:pageLegal                                   
  GET      /modals/account/tos                                         UserFrosting\Sprinkle\Account\Controller\AccountController:getModalAccountTos                    
  GET      /modals/dashboard/clear-cache                               UserFrosting\Sprinkle\Admin\Controller\AdminController:getModalConfirmClearCache                 
  GET      /modals/groups/confirm-delete                               UserFrosting\Sprinkle\Admin\Controller\GroupController:getModalConfirmDelete                     
  GET      /modals/groups/create                                       UserFrosting\Sprinkle\Admin\Controller\GroupController:getModalCreate                            
  GET      /modals/groups/edit                                         UserFrosting\Sprinkle\Admin\Controller\GroupController:getModalEdit                              
  GET      /modals/roles/confirm-delete                                UserFrosting\Sprinkle\Admin\Controller\RoleController:getModalConfirmDelete                      
  GET      /modals/roles/create                                        UserFrosting\Sprinkle\Admin\Controller\RoleController:getModalCreate                             
  GET      /modals/roles/edit                                          UserFrosting\Sprinkle\Admin\Controller\RoleController:getModalEdit                               
  GET      /modals/roles/permissions                                   UserFrosting\Sprinkle\Admin\Controller\RoleController:getModalEditPermissions                    
  GET      /modals/users/confirm-delete                                UserFrosting\Sprinkle\Admin\Controller\UserController:getModalConfirmDelete                      
  GET      /modals/users/create                                        UserFrosting\Sprinkle\Admin\Controller\UserController:getModalCreate                             
  GET      /modals/users/edit                                          UserFrosting\Sprinkle\Admin\Controller\UserController:getModalEdit                               
  GET      /modals/users/password                                      UserFrosting\Sprinkle\Admin\Controller\UserController:getModalEditPassword                       
  GET      /modals/users/roles                                         UserFrosting\Sprinkle\Admin\Controller\UserController:getModalEditRoles                          
  GET      /permissions                              uri_permissions   UserFrosting\Sprinkle\Admin\Controller\PermissionController:pageList                             
  GET      /permissions/p/{id}                                         UserFrosting\Sprinkle\Admin\Controller\PermissionController:pageInfo                             
  GET      /privacy                                                    UserFrosting\Sprinkle\Core\Controller\CoreController:pagePrivacy                                 
  GET      /roles                                    uri_roles         UserFrosting\Sprinkle\Admin\Controller\RoleController:pageList                                   
  GET      /roles/r/{slug}                                             UserFrosting\Sprinkle\Admin\Controller\RoleController:pageInfo                                   
  GET      /users                                    uri_users         UserFrosting\Sprinkle\Admin\Controller\UserController:pageList                                   
  GET      /users/u/{user_name}                                        UserFrosting\Sprinkle\Admin\Controller\UserController:pageInfo                                   
 -------- ----------------------------------------- ----------------- ------------------------------------------------------------------------------------------------- `

**Comment by lcharette** [comment]
Weird... I still can't replicate, and everything should be fine config wise. You even say navigating to `http://http://localhost/formgenerator/new` get you the unstyled form??

The only difference I see are in the url params encoding : 

Try navigating to both : 
1) http://localhost/formgenerator/new?box_id=formGeneratorModal&toggle=modal&formurl=/formgenerator/new&_1575265868584
2) http://http://localhost/formgenerator/new?box_id=formGeneratorModal&toggle=modal&formurl=%2Fformgenerator%2Fnew&_1575265868584

**Comment by lcharette** [comment]
Also, which browser are you using?

**Comment by silicon755** [comment]
> Also, which browser are you using?

Tried in both Firefox & Chrome
![Screenshot from 2019-12-03 17-41-10](https://user-images.githubusercontent.com/22223504/70061258-039ccd00-15f5-11ea-94f5-e0c012881462.png)

**Comment by silicon755** [comment]
> Weird... I still can't replicate, and everything should be fine config wise. You even say navigating to `http://http://localhost/formgenerator/new` get you the unstyled form??
> 
> The only difference I see are in the url params encoding :
> 
> Try navigating to both :
> 
>     1. http://localhost/formgenerator/new?box_id=formGeneratorModal&toggle=modal&formurl=/formgenerator/new&_1575265868584
> 
>     2. http://http://localhost/formgenerator/new?box_id=formGeneratorModal&toggle=modal&formurl=%2Fformgenerator%2Fnew&_1575265868584

I tried the above links and they are all getting me to the unstyled form.

**Comment by lcharette** [comment]
Very weird. I think your system will need an exorcism...

**Comment by silicon755** [comment]
On clicking "Create project" button, I get the following console logs
`VM470:1 GET http://localhost/formgenerator/new?box_id=formGeneratorModal&toggle=modal&formurl=%2Fformgenerator%2Fnew&_=1575383941199 404 (Not Found)
(anonymous) @ VM470:1
send @ jquery-3.2.1.min.js:4
ajax @ jquery-3.2.1.min.js:4
_fetchForm @ widget-formGenerator.js:86
e @ jquery-3.2.1.min.js:2
dispatch @ jquery-3.2.1.min.js:3
q.handle @ jquery-3.2.1.min.js:3`

**Comment by lcharette** [comment]
Which is weird and doesn't make sense, since you can access it manually....

http://localhost/formgenerator/new?box_id=formGeneratorModal&toggle=modal&formurl=%2Fformgenerator%2Fnew&_=1575383941199

Did you try implementing it manually, in your sprinkle, without using the example?

**Comment by silicon755** [comment]
> Which is weird and doesn't make sense, since you can access it manually....
> 
> http://localhost/formgenerator/new?box_id=formGeneratorModal&toggle=modal&formurl=%2Fformgenerator%2Fnew&_=1575383941199
> 
> Did you try implementing it manually, in your sprinkle, without using the example?

I have not tried to implement it manually, let me try and revert
